spring:
  security:
    user:
      name: event_service_user
      password: password
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/SSP
    username: postgres
    password: 1
  flyway:
    schemas:
      - public
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info